#ifndef MACHINE_H
#define MACHINE_H

#define PIN_LED_RED GPIO_PIN_2
#define PORT_LED_RED GPIOA
#define PIN_LED_BLUE GPIO_PIN_5
#define PORT_LED_BLUE GPIOA

// A
#define PIN_HIN_A  GPIO_PIN_1
#define PIN_LIN_A  GPIO_PIN_0
#define PORT_HIN_A GPIOA
#define PORT_LIN_A GPIOA
// B
#define PIN_HIN_B  GPIO_PIN_14
#define PIN_LIN_B  GPIO_PIN_15
#define PORT_HIN_B GPIOC
#define PORT_LIN_B GPIOC
// C
#define PIN_HIN_C  GPIO_PIN_6
#define PIN_LIN_C  GPIO_PIN_11
#define PORT_HIN_C GPIOB
#define PORT_LIN_C GPIOA

#define ADC_CHANNEL_PHASE_A ADC_CHANNEL_6
#define ADC_CHANNEL_PHASE_B ADC_CHANNEL_7
#define ADC_CHANNEL_PHASE_C ADC_CHANNEL_8


#endif /* MACHINE_H */
